services:
  remote-mcp-proxy:
    build: .
    container_name: remote-mcp-proxy
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
    environment:
      - GO_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.remote-mcp-proxy.rule=Host(`mcp.${DOMAIN}`)
      - traefik.http.routers.remote-mcp-proxy.entrypoints=websecure
      - traefik.http.routers.remote-mcp-proxy.tls.certresolver=myresolver
      - traefik.http.services.remote-mcp-proxy.loadbalancer.server.port=8080

networks:
  proxy:
    external: true